language: python
python:
  - "3.6"
cache: pip
# command to install dependencies

services:
- postgresql 

before_script:
  - psql -c "CREATE USER postgres;" -U postgres

  - psql -c 'CREATE DATABASE fastfoodfast;' -U postgres

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install nose

# command to run tests
script:
  - pytest tests  --cov=tests --cov-report term-missing
 

#for coveralls
after_success:
  - coveralls

